// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApiSample.BL.Mappings.Test
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("InsertProductModel轉換為ProductModel功能", Description="提供給 BL層\r\n使用者輸入InsertProductModel資料，將資料轉換為ProductModel", SourceFile="InsertProductModel轉換為ProductModel功能.feature", SourceLine=1)]
    public partial class InsertProductModel轉換為ProductModel功能Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "InsertProductModel轉換為ProductModel功能.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "InsertProductModel轉換為ProductModel功能", "提供給 BL層\r\n使用者輸入InsertProductModel資料，將資料轉換為ProductModel", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line 7
   testRunner.Given("使用GiftModelMappingProfile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 8
   testRunner.Given("使用ProductModelMappingProfile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("輸入InsertProductModel資料， 轉換為Product Model", SourceLine=9)]
        public virtual void 輸入InsertProductModel資料轉換為ProductModel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("輸入InsertProductModel資料， 轉換為Product Model", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 6
  this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Price",
                        "Cost",
                        "Introduction",
                        "StartListingAt",
                        "FinishListingAt",
                        "StartSellAt",
                        "FinishSellAt",
                        "CategoryId",
                        "Gifts"});
            table1.AddRow(new string[] {
                        "Product",
                        "200",
                        "100",
                        "Description",
                        "2013-10-01",
                        "2014-10-01",
                        "2013-10-02",
                        "2014-09-30",
                        "1",
                        "Gift1:AAA"});
#line 11
 testRunner.Given("輸入資料為", ((string)(null)), table1, "假設");
#line 14
 testRunner.When("執行轉換為Product Model", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Price",
                        "Cost",
                        "Description",
                        "ListingStartTime",
                        "ListingEndTime",
                        "SellingStartTime",
                        "SellingEndTime",
                        "CategoryId"});
            table2.AddRow(new string[] {
                        "Product",
                        "200",
                        "100",
                        "Description",
                        "2013-10-01",
                        "2014-10-01",
                        "2013-10-02",
                        "2014-09-30",
                        "1"});
#line 15
 testRunner.Then("Product Model為", ((string)(null)), table2, "那麼");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description"});
            table3.AddRow(new string[] {
                        "Gift1",
                        "AAA"});
#line 18
 testRunner.And("包含Gift List", ((string)(null)), table3, "並且");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
