// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApiSample.DA.Repositories.Test
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("分類商品查詢功能", Description="提供給 BL層\r\n查詢分類下的商品有哪些，並自動判斷商品是否在上架時間之內", SourceFile="分類商品查詢功能.feature", SourceLine=2)]
    [TechTalk.SpecRun.IgnoreAttribute()]
    public partial class 分類商品查詢功能Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "分類商品查詢功能.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "分類商品查詢功能", "提供給 BL層\r\n查詢分類下的商品有哪些，並自動判斷商品是否在上架時間之內", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table1.AddRow(new string[] {
                        "1",
                        "Foods"});
            table1.AddRow(new string[] {
                        "2",
                        "Drinks"});
            table1.AddRow(new string[] {
                        "3",
                        "Fruits"});
#line 8
 testRunner.Given("資料庫中有分類資料", ((string)(null)), table1, "假設");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "CategoryId",
                        "Name",
                        "Price",
                        "Cost",
                        "ListingStartTime",
                        "ListingEndTime",
                        "SellingStartTime",
                        "SellingEndTime",
                        "IsValid"});
            table2.AddRow(new string[] {
                        "1",
                        "Hamburger",
                        "99",
                        "50",
                        "2013-10-01",
                        "2014-10-01",
                        "2013-10-01",
                        "2014-10-01",
                        "true"});
            table2.AddRow(new string[] {
                        "1",
                        "Sandwitch",
                        "89",
                        "40",
                        "2013-10-01",
                        "2014-10-01",
                        "2013-10-01",
                        "2014-10-01",
                        "true"});
            table2.AddRow(new string[] {
                        "2",
                        "Orange Juice",
                        "40",
                        "20",
                        "2013-10-01",
                        "2014-11-01",
                        "2013-10-01",
                        "2014-10-01",
                        "true"});
            table2.AddRow(new string[] {
                        "2",
                        "Milk",
                        "35",
                        "20",
                        "2013-11-01",
                        "2014-11-01",
                        "2013-11-01",
                        "2014-10-01",
                        "true"});
            table2.AddRow(new string[] {
                        "3",
                        "Watermelon",
                        "50",
                        "25",
                        "2013-10-01",
                        "2014-11-01",
                        "2013-11-01",
                        "2014-10-01",
                        "true"});
            table2.AddRow(new string[] {
                        "3",
                        "Banana",
                        "50",
                        "25",
                        "2013-10-01",
                        "2014-11-01",
                        "2013-11-01",
                        "2014-10-01",
                        "false"});
#line 13
 testRunner.And("資料庫中有產品資料", ((string)(null)), table2, "並且");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("根據分類序號查詢商品，假設分類下所有商品上架時間都符合，查詢得到所有商品", SourceLine=21)]
        public virtual void 根據分類序號查詢商品假設分類下所有商品上架時間都符合查詢得到所有商品()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("根據分類序號查詢商品，假設分類下所有商品上架時間都符合，查詢得到所有商品", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 23
 testRunner.Given("當查詢分類1的商品時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 24
 testRunner.When("執行分類商品查詢", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Price"});
            table3.AddRow(new string[] {
                        "Hamburger",
                        "99"});
            table3.AddRow(new string[] {
                        "Sandwitch",
                        "89"});
#line 25
 testRunner.Then("得到商品", ((string)(null)), table3, "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("根據分類序號查詢商品，假設分類下有商品上架時間還沒到，查詢得到符合的商品", SourceLine=29)]
        public virtual void 根據分類序號查詢商品假設分類下有商品上架時間還沒到查詢得到符合的商品()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("根據分類序號查詢商品，假設分類下有商品上架時間還沒到，查詢得到符合的商品", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 31
 testRunner.Given("當查詢分類2的商品時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 32
 testRunner.When("執行分類商品查詢", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Price"});
            table4.AddRow(new string[] {
                        "Orange Juice",
                        "40"});
#line 33
 testRunner.Then("得到商品", ((string)(null)), table4, "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("根據分類序號查詢商品，過濾IsValid為false(代表刪除)的商品，只查詢服和的商品", SourceLine=36)]
        public virtual void 根據分類序號查詢商品過濾IsValid為False代表刪除的商品只查詢服和的商品()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("根據分類序號查詢商品，過濾IsValid為false(代表刪除)的商品，只查詢服和的商品", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 38
 testRunner.Given("當查詢分類3的商品時", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line 39
 testRunner.When("執行分類商品查詢", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Price"});
            table5.AddRow(new string[] {
                        "Watermelon",
                        "50"});
#line 40
 testRunner.Then("得到商品", ((string)(null)), table5, "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
