// <auto-generated />
namespace ApiSample.DA.Tables.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSystemInfoField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSystemInfoField));
        
        string IMigrationMetadata.Id
        {
            get { return "201310051434491_AddSystemInfoField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
