// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApiSample.Utility.Hooks.Test
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("刪除資料改為更新IsValid欄位功能", Description="提供給 DA層\r\n當系統進行Delete時，並不會真的刪除資料，而是以更新IsValid欄位為False取代\r\n這樣日後想回復資料時，可以方便取回", SourceFile="刪除資料改為更新IsValid欄位功能.feature", SourceLine=1)]
    public partial class 刪除資料改為更新IsValid欄位功能Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "刪除資料改為更新IsValid欄位功能.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "刪除資料改為更新IsValid欄位功能", "提供給 DA層\r\n當系統進行Delete時，並不會真的刪除資料，而是以更新IsValid欄位為False取代\r\n這樣日後想回復資料時，可以方便取回", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("ShopContext刪除時會以更新IsValid為false取代", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("當執行刪除資料時，以更新IsValid欄位為False取代", SourceLine=9)]
        public virtual void 當執行刪除資料時以更新IsValid欄位為False取代()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("當執行刪除資料時，以更新IsValid欄位為False取代", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "Fruits"});
#line 11
 testRunner.Given("新增分類資料", ((string)(null)), table1, "假設");
#line 14
 testRunner.When("執行刪除分類Fruits", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "IsValid"});
            table2.AddRow(new string[] {
                        "Fruits",
                        "false"});
#line 15
 testRunner.Then("資料庫中包含資料", ((string)(null)), table2, "那麼");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
